sudo: required

language: c

services:
  - docker

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix
  - make

script:
  - cd openresty-1.15.6.1rc0
  - ./configure
  - make
  - make install
