sudo: required

language: c

services:
  - docker

os:
  - linux

sudo: required

env:
  - VERSION=1.15.6.1rc0
  
before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix curl


script:
  - ROOT=$(pwd)
  - mkdir -p /tmp
  - mkdir -p /opt
  - mkdir -p /opt/openssl
  - curl -fsSL https://www.openssl.org/source/openssl-1.1.0j.tar.gz -o /tmp/openssl.tar.gz
  - tar -C /opt/openssl -xzf /tmp/openssl.tar.gz --strip-components 1
  - cd /opt/openssl
  - ls 
  - ./config
  - make 1> /dev/null
  - make install_sw 1> /dev/null
  - ldconfig
  - cd $ROOT
  - make
  - cd $ROOT/openresty-$VERSION
  - ./configure
  - make
